title: "Awala"
description: "The network on which humankind can truly rely"
permalink: /blog/:slug

defaults:
  - values:
      description: null
      breadcrumbs: null
      pagination:
        previous: null
        next: null
      js:
        libraries: []
        scripts: []
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      breadcrumbs: [blog.html]
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      breadcrumbs: [blog.html]

markdown: kramdown
liquid:
  strict_variables: true
  strict_filters: true
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .idea
  - README.md

# Custom variables

javascript_libraries:
  cash-dom:
    # https://www.jsdelivr.com/package/npm/cash-dom
    version: 8.1.0
    digest: "sha256-xb3jchN35UY4gwqlR0mSg/dtv25q4yWmXmIg/WscJYo="
    path: "dist/cash.min.js"
  mustache:
    # https://www.jsdelivr.com/package/npm/mustache
    version: 4.2.0
    digest: "sha256-1/0GA1EkYejtvYFoa+rSq4LfM4m5zKI13Z1bQIhI4Co="
    path: "mustache.min.js"
