title: "Relaynet"
description: "Relaynet: The resilient and modern computer network"

google_analytics: UA-22641273-3
twitter_username: relaynet_
github_username: relaynet

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
